export const data = [
  {
    timestamp: 1608067551,
    fileName: 'filestatus/CHO-Boston-OracleHours.txt',
    file: 'CHO-Boston-OracleHours.txt',
    workStep: 'Transform',
    plan: 'CHO',
    vendor: 'TheHatford',
    message: 'Error',
  },
  {
    timestamp: 1608067551,
    fileName: 'filestatus/CHO-Boston-OracleHours.txt',
    file: 'CHO-Boston-OracleHours.txt',
    workStep: 'Transform',
    plan: 'CHO',
    vendor: 'TheHatford',
    message: 'Error',
  },
  {
    timestamp: 1608067551,
    fileName: 'filestatus/CHO-Boston-OracleHours.txt',
    file: 'CHO-Boston-OracleHours.txt',
    workStep: 'Transform',
    plan: 'CHO',
    vendor: 'TheHatford',
    message: 'Error',
  },
  {
    timestamp: 1608068919,
    fileName: 'filestatus/CHO-Boston-OracleHours.txt',
    file: 'CHO-Boston-OracleHours.txt',
    workStep: 'Transform',
    plan: 'CHO',
    vendor: 'TheHatford',
    message: 'Error',
  },
  {
    timestamp: 1608068919,
    fileName: 'filestatus/CHO-Boston-OracleHours.txt',
    file: 'CHO-Boston-OracleHours.txt',
    workStep: 'Transform',
    plan: 'CHO',
    vendor: 'TheHatford',
    message: 'Error',
  },
  {
    timestamp: 1608068919,
    fileName: 'filestatus/CHO-Boston-OracleHours.txt',
    file: 'CHO-Boston-OracleHours.txt',
    workStep: 'Transform',
    plan: 'CHO',
    vendor: 'TheHatford',
    message: 'Error',
  },
  {
    timestamp: 1608068919,
    fileName: 'filestatus/CHO-Boston-OracleHours.txt',
    file: 'CHO-Boston-OracleHours.txt',
    workStep: 'Transform',
    plan: 'CHO',
    vendor: 'TheHatford',
    message: 'Error',
  },
  {
    timestamp: 1608068919,
    fileName: 'filestatus/CHO-Boston-OracleHours.txt',
    file: 'CHO-Boston-OracleHours.txt',
    workStep: 'Transform',
    plan: 'CHO',
    vendor: 'TheHatford',
    message: 'Error',
  },
  {
    timestamp: 1608068919,
    fileName: 'filestatus/CHO-Boston-OracleHours.txt',
    file: 'CHO-Boston-OracleHours.txt',
    workStep: 'Transform',
    plan: 'CHO',
    vendor: 'TheHatford',
    message: 'Error',
  },
  {
    timestamp: 1608068919,
    fileName: 'filestatus/CHO-Boston-OracleHours.txt',
    file: 'CHO-Boston-OracleHours.txt',
    workStep: 'Transform',
    plan: 'CHO',
    vendor: 'TheHatford',
    message: 'Error',
  },
];
