version: 0.2
env:
  secrets-manager:
    LOGIN: sonarqube/cdx-dash-react-ts:sonartoken
    HOST: sonarqube/cdx-dash-react-ts:host
    PROJECT: sonarqube/cdx-dash-react-ts:project
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
    - echo In the pre_build phase...
    - echo https://services.gradle.org/distributions/
    - wget https://services.gradle.org/distributions/gradle-6.6.1-all.zip
    - unzip -d /opt/gradle gradle-6.6.1-all.zip
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
    - unzip ./sonar-scanner-cli-4.6.2.2472-linux.zip
    - export PATH=$PATH:/sonar-scanner-4.6.2.2472-linux/bin/
  build:
    commands:
    - echo Build started on `date`
    - echo Starting build `date`
    - echo Current directory is `pwd`
    - pwd
    - whereis gradle
    - which gradle
    - /opt/gradle/gradle-6.6.1/bin/gradle -version
    - /opt/gradle/gradle-6.6.1/bin/gradle clean jar yarnTest
    - sonar-scanner.sh -D"sonar.projectKey=$PROJECT" -D"sonar.sources=src" -D"sonar.host.url=$HOST" -D"sonar.login=$LOGIN"
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
  - 'build/libs/*.jar'

